project:
  type: website
  output-dir: docs


website:
  title: "Uploading Metadata"
  navbar:
    right: 
      - href: index.qmd
        text: Home
      - FAQs.qmd
      - Links.qmd
    background: "#8B814C"
    search: true
    pinned: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    highlight: pygments
    anchor-sections: false
    smooth-scroll: true
    mainfont: "Segoe UI"
    fontcolor: "#8B814C"
    monobackgroundcolor: "#FAFAF5"
    backgroundcolor: "#FAFAF5"
    headercolor: "#191970"
    code-line-numbers: true
    code-block-bg: "#FFFFFF"
    code-fold: true
    code-background: true
    cap-location: top
    margin-left: "0in"
    margin-right: "0in"
    fig-width: 12
    fig-height: 8
    link-external-newwindow: true
    

execute: 
  echo: false
  message: false
  warning: false

